- name: Download R
  win_get_url:
    url : 'https://cran.biotools.fr/bin/windows/base/old/{{ r_version }}/R-{{ r_version }}-win.exe'
    dest: 'C:\Windows\Temp\R-win.exe'

# should work with ansible > 2.10
#- name: Install R Project
#  ansible.windows.win_package:
#    path: C:\Windows\Temp\R-win.exe
#    arguments: /VERYSILENT /DIR='C:\R\'
#    state: present
 
# Old version
- name: copy R script
  win_copy:
    src: ./files/install-r.ps1
    dest: 'C:\Windows\Temp\'
    remote_src: no
- name: Install R
  win_command: powershell.exe -File C:\Windows\Temp\install-r.ps1

- name: Configure R env
  win_command: Rscript -e "dir.create(Sys.getenv('R_LIBS_USER'), recursive=TRUE)"

- name: create .Renviron
  ansible.windows.win_file:
    path: C:\Users\vmr\.Renviron
    state: touch
