stages:
  - build

Gen-Win10Ent-Virtualbox-box:
  tags:
    - "vb"
    - "ansible"
    - "vagrant"
  stage: build
  script:
    - ./build.sh -c "$VAGRANTCLOUDTOKEN" -i "$SOURCE_PATH/Windows/19042.631.201119-0144.20h2_release_svc_refresh_CLIENTENTERPRISEEVAL_OEMRET_x64FRE_en-us.iso" -s "32C7B0A51A48CC4F67C250BE4FE2B384FEBB9CC864C5B77A052D4E2845394EAC" -v "Enterprise"
  when: manual  

Gen-Win10Pro-Virtualbox-box:
  tags:
    - "vb"
    - "ansible"
    - "vagrant"
  stage: build
  script:
    - ./build.sh -c "$VAGRANTCLOUDTOKEN" -i "$SOURCE_PATH/Windows/Win10_20H2_v2_EnglishInternational_x64.iso" -s "BD9E41BDF9E23DCF5A0592F3BFE794584C80F1415727ED234E8929F656221836" -v "Pro"
  when: manual  
