---
- name: Windows hosts ping
  hosts: all
  tasks:
    - name: ping
      win_ping:
    #- name: Install security updates
    #  win_updates:
    #    category_names:
    #      - SecurityUpdates
    #    reboot: yes

- name: install R, Rtools, dependencies and sshd
  hosts: all
  vars:
    - r_cran_mirror: https://cloud.r-project.org
  roles:
    - R
    - Rtools
    - msys2
    - R-packages
    - MikTex
    - Pandoc
    - cicd

- name: Clean
  hosts: all
  tasks:
    - name: clean Temp dir
      win_command: cmd.exe /c DEL /F/Q/S C:\Windows\Temp\*.*

- name: Reboot after install
  hosts: all
  tasks: 
    - name: Reboot windows
      win_reboot:
        reboot_timeout: 360
        post_reboot_delay: 120

